# Generated by Django 5.0.4 on 2024-07-02 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_created_at_alter_bid_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
